# Generated by Django 5.1.3 on 2024-11-21 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='alto_falantes',
            new_name='autoFalantes',
        ),
        migrations.RenameField(
            model_name='checklist',
            old_name='conexao_internet',
            new_name='internet',
        ),
        migrations.RenameField(
            model_name='checklist',
            old_name='memoria_ram',
            new_name='ram',
        ),
        migrations.RenameField(
            model_name='checklist',
            old_name='sistema_operacional',
            new_name='sistema',
        ),
    ]
